const { chromium } = require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
require('node:fs').mkdirSync(path.join(__dirname,'artifacts'),{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);await page.waitForTimeout(1000);await page.screenshot({path:__dirname+'/artifacts/desktop.png',fullPage:true});await page.getByRole('button',{name:'Pause',exact:true}).click();let before=await page.locator('#time1').textContent();await page.waitForTimeout(250);assert.equal(await page.locator('#time1').textContent(),before);await page.locator('#preset').selectOption('weak');assert.match(await page.locator('#rate1').textContent(),/99\.999/);await page.getByRole('button',{name:'Reset',exact:true}).click();assert.equal(await page.locator('#preset').inputValue(),'compact');let canvas=page.locator('canvas');let box=await canvas.boundingBox();await page.mouse.move(box.x+200,box.y+150);await page.mouse.down();await page.mouse.move(box.x+300,box.y+200);await page.mouse.up();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();
const state=await page.evaluate(()=>JSON.stringify(spacetimeModel.bodies.map(b=>[b.p,b.v])));
await page.locator('#mass').fill('1.3');await page.locator('#mass').dispatchEvent('input');
assert.equal(await page.evaluate(()=>JSON.stringify(spacetimeModel.bodies.map(b=>[b.p,b.v]))),state);
await page.locator('#extent').fill('18');await page.locator('#extent').dispatchEvent('input');
await page.locator('#trails').uncheck();await page.locator('#orbitPreset').selectOption('escape');
assert.ok(await page.evaluate(()=>spacetimeModel.bodies.every(b=>b.status==='orbiting')));
await page.locator('#orbitPreset').selectOption('solar');assert.equal(await page.evaluate(()=>spacetimeModel.bodies.length),8);
assert.match(await page.locator('#orbitStatus').textContent(),/Mercury.*Neptune/);
await page.getByRole('button',{name:'Restart orbits',exact:true}).click();
await page.locator('#extent').fill('18');await page.locator('#extent').dispatchEvent('input');
await page.locator('#starBrightness').fill('0');await page.locator('#starBrightness').dispatchEvent('input');
await page.locator('#brightness').fill('500');await page.locator('#brightness').dispatchEvent('input');
await page.getByRole('button',{name:'Play',exact:true}).click();await page.waitForTimeout(500);
await page.screenshot({path:__dirname+'/artifacts/orbits-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:__dirname+'/artifacts/mobile.png',fullPage:true});await page.locator('summary').click();assert.ok(await page.locator('details').evaluate(x=>x.open));assert.deepEqual(errors,[]);await browser.close();console.log('PASS: desktop/mobile render, no JS errors, pause, weak preset, reset, camera drag, zoom, expandable explanation, no mobile horizontal overflow.');})().catch(e=>{console.error(e);process.exit(1)});
